openapi: 3.0.0
info:
  title: Generic Server
  version: 1.0.0
paths:
  /location/{rider_id}:
    get:
      summary: Get rider's location history
      parameters:
        - in: path
          name: rider_id
          schema:
            type: string
        - in: query
          name: max
          schema:
            type: integer
      responses:
        '404':
          description: Rider not found
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetLocationHistoryResponse'

  /location/{rider_id}/now:
    post:
      summary: Create entity
      parameters:
        - in: path
          name: rider_id
          schema:
            type: string
        - in: body
          name: body
          schema:
            $ref: '#/components/schemas/LocationEntry'
      responses:
        '200':
          description: Success
components:
  schemas:
    LocationEntry:
      type: object
      properties:
        lat:
          type: number
        long:
          type: number
      required:
        - long
        - lat
    
    GetLocationHistoryResponse:
      type: object
      properties:
        rider_id:
          type: string
        history:
          type: array
          items:
            $ref: "#/components/schemas/LocationEntry"
      required:
        - rider_id
        - history
      