// Package servertest provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package servertest

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// GetLocationHistoryResponse defines model for GetLocationHistoryResponse.
type GetLocationHistoryResponse struct {
	History []LocationEntry `json:"history"`
	RiderId string          `json:"rider_id"`
}

// LocationEntry defines model for LocationEntry.
type LocationEntry struct {
	Lat  float32 `json:"lat"`
	Long float32 `json:"long"`
}

// GetLocationRiderIdParams defines parameters for GetLocationRiderId.
type GetLocationRiderIdParams struct {
	Max *int `form:"max,omitempty" json:"max,omitempty"`
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetLocationRiderId request
	GetLocationRiderId(ctx context.Context, riderId string, params *GetLocationRiderIdParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostLocationRiderIdNow request
	PostLocationRiderIdNow(ctx context.Context, riderId string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetLocationRiderId(ctx context.Context, riderId string, params *GetLocationRiderIdParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetLocationRiderIdRequest(c.Server, riderId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostLocationRiderIdNow(ctx context.Context, riderId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostLocationRiderIdNowRequest(c.Server, riderId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetLocationRiderIdRequest generates requests for GetLocationRiderId
func NewGetLocationRiderIdRequest(server string, riderId string, params *GetLocationRiderIdParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "rider_id", runtime.ParamLocationPath, riderId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/location/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Max != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "max", runtime.ParamLocationQuery, *params.Max); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostLocationRiderIdNowRequest generates requests for PostLocationRiderIdNow
func NewPostLocationRiderIdNowRequest(server string, riderId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "rider_id", runtime.ParamLocationPath, riderId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/location/%s/now", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetLocationRiderIdWithResponse request
	GetLocationRiderIdWithResponse(ctx context.Context, riderId string, params *GetLocationRiderIdParams, reqEditors ...RequestEditorFn) (*GetLocationRiderIdResponse, error)

	// PostLocationRiderIdNowWithResponse request
	PostLocationRiderIdNowWithResponse(ctx context.Context, riderId string, reqEditors ...RequestEditorFn) (*PostLocationRiderIdNowResponse, error)
}

type GetLocationRiderIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GetLocationHistoryResponse
}

// Status returns HTTPResponse.Status
func (r GetLocationRiderIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetLocationRiderIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostLocationRiderIdNowResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PostLocationRiderIdNowResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostLocationRiderIdNowResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetLocationRiderIdWithResponse request returning *GetLocationRiderIdResponse
func (c *ClientWithResponses) GetLocationRiderIdWithResponse(ctx context.Context, riderId string, params *GetLocationRiderIdParams, reqEditors ...RequestEditorFn) (*GetLocationRiderIdResponse, error) {
	rsp, err := c.GetLocationRiderId(ctx, riderId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetLocationRiderIdResponse(rsp)
}

// PostLocationRiderIdNowWithResponse request returning *PostLocationRiderIdNowResponse
func (c *ClientWithResponses) PostLocationRiderIdNowWithResponse(ctx context.Context, riderId string, reqEditors ...RequestEditorFn) (*PostLocationRiderIdNowResponse, error) {
	rsp, err := c.PostLocationRiderIdNow(ctx, riderId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostLocationRiderIdNowResponse(rsp)
}

// ParseGetLocationRiderIdResponse parses an HTTP response from a GetLocationRiderIdWithResponse call
func ParseGetLocationRiderIdResponse(rsp *http.Response) (*GetLocationRiderIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetLocationRiderIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GetLocationHistoryResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostLocationRiderIdNowResponse parses an HTTP response from a PostLocationRiderIdNowWithResponse call
func ParsePostLocationRiderIdNowResponse(rsp *http.Response) (*PostLocationRiderIdNowResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostLocationRiderIdNowResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/6xTTWvcQAz9K0Yt9GLibZuTr6WkgVJKcgyhzNra3QlraaKRky7L/vcirfczTughJ8+M",
	"pCe99+Q1NNwlJiTNUK8hNwvsgh+vUH9yEzQy/YhZWVY3mBNTRosm4YSiET13sU2wY1Ts/O2j4Axq+FAd",
	"OlQDfLUD/k4qK9iUoKuEUEMQCX6X2KL8ia0BDbGsEmkOG4viYx8FW6jvDpnlfor7PR5PH7BRAzzt+ILA",
	"MuhRK+q7KYqVLZnmI4GzGTyrdJCXvS050owdJurSYldIKLEpblGeUKCEJ5QcmaCGzxeTi4m15oQUUoQa",
	"vvpTCSnowqetlgObar2jv7H3OToLI+bh69Z77X28seTr1qEkdKgoGeq7NUTrbPBQAoXORjzSdevaqBVD",
	"6WOPsjrUduHvWFkkxbnLd2/6bZfJCX2ZTOzTMCmScwgpLeNA8iGbMusjwLd26429dS9azI3EpFu5b/um",
	"wZxN8MvJpWGfxl2ygliLGffUuvW577pgW2TaFi7Up1zsPCl2a2ipY05VxM++gZxH7PrN+dyvX/z8/pZN",
	"uT1ybLj9n8Jnf+9rbr4i9ImA3wSDYoGkUQ1qs/kXAAD//4nbH6CSBAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
